Repository fulflix/fulflix, pull requests merged in 2024-09, with the labels that each got.

#1 docs: initial github pr template
  .gihub/PULL_REQUEST_TEMPLATE.md
Labels: build, chore, config, feat

#3 Build/initial web common module
  settings.gradle
  web-common/build.gradle.kts
  web-common/src/main/java/io/fulflix/common/WebCommonConfig.java
  web-common/src/main/java/io/fulflix/common/context/UserContextConfig.java
  web-common/src/main/java/io/fulflix/common/context/UserContextHolder.java
  web-common/src/main/java/io/fulflix/common/context/UserContextHolderInterceptor.java
  web-common/src/main/java/io/fulflix/common/context/annotation/CurrentUser.java
  web-common/src/main/java/io/fulflix/common/context/annotation/CurrentUserArgumentResolver.java
  web-common/src/main/java/io/fulflix/common/context/annotation/CurrentUserResolverConfig.java
  web-common/src/main/java/io/fulflix/common/jpa/JpaConfig.java
  web-common/src/main/java/io/fulflix/common/jpa/audit/Auditable.java
  web-common/src/main/java/io/fulflix/common/jpa/audit/CommonAuditFields.java
  web-common/src/main/java/io/fulflix/common/jpa/audit/UserAuditorAwareConfig.java
  web-common/src/main/java/io/fulflix/common/web/utils/PropertiesCombineUtils.java
  web-common/src/main/java/io/fulflix/common/web/utils/UriComponentUtils.java
  web-common/src/main/resources/application.yml
  web-common/src/main/resources/properties/datasource.yml
  web-common/src/main/resources/properties/jpa.yml
Labels: build, chore, config, feat

#4 build: initial auth-app module for authentication and authorization
  auth-app/build.gradle
  auth-app/src/main/java/io/fulflix/auth/AuthApp.java
  auth-app/src/main/resources/application-auth.yml
  auth-app/src/test/java/io/fulflix/auth/AuthAppTests.java
  settings.gradle
Labels: build, config

#10 enhance: encode user password
  auth-app/build.gradle
  auth-app/src/main/java/io/fulflix/auth/api/dto/UserCreateRequest.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
  auth-app/src/main/java/io/fulflix/auth/config/PasswordEncoderConfig.java
  auth-app/src/main/java/io/fulflix/auth/domain/EncodedPassword.java
  auth-app/src/main/java/io/fulflix/infra/client/UserAppClient.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
Labels: build, enhance, test

#11 feat: authorization api
  auth-app/build.gradle
  auth-app/src/main/java/io/fulflix/auth/AuthApp.java
  auth-app/src/main/java/io/fulflix/auth/api/AuthController.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/SignInRequest.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/SignUpRequest.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/UserCreateRequest.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthenticationService.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
  auth-app/src/main/java/io/fulflix/auth/application/TokenIssueService.java
  auth-app/src/main/java/io/fulflix/auth/domain/FulflixPrincipal.java
  auth-app/src/main/java/io/fulflix/auth/exception/AuthErrorCode.java
  auth-app/src/main/java/io/fulflix/auth/exception/AuthException.java
  auth-app/src/main/java/io/fulflix/auth/utils/jwt/JwtProperties.java
  auth-app/src/main/java/io/fulflix/auth/utils/jwt/JwtProvider.java
  auth-app/src/main/java/io/fulflix/auth/utils/jwt/SigningUtils.java
  auth-app/src/main/java/io/fulflix/infra/client/UserAppClient.java
  auth-app/src/main/java/io/fulflix/infra/client/dto/UserDetailsResponse.java
  auth-app/src/main/resources/application-auth.yml
  auth-app/src/main/resources/properties/jwt.yml
  auth-app/src/test/java/io/fulflix/auth/api/AuthApiTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthControllerTest.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthServiceTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/fixture/AuthTestFixture.java
  auth-app/src/test/java/io/fulflix/auth/utils/jwt/JwtProviderTest.java
  auth-app/src/test/java/io/fulflix/auth/utils/jwt/TokenTestHelper.java
Labels: chore, feat

#12 build: init user-app module
  settings.gradle
  user-app/build.gradle
  user-app/src/main/java/io/fulflix/user/UserApp.java
  user-app/src/main/resources/application-user.yml
Labels: build

#14 config:logging configurations
  .gitignore
  app-common/src/main/resources/application.yml
  app-common/src/main/resources/logback-spring-dev.xml
  app-common/src/main/resources/logback-spring-prd.xml
  app-common/src/main/resources/properties/jpa.yml
  app-common/src/main/resources/properties/logging.yml
Labels: chore, config

#15 chore: polishing web common
  web-common/src/main/resources/application.properties
  web-common/src/test/java/io/fulflix/common/web/base/TestBase.java
  web-common/src/test/java/io/fulflix/common/web/fixture/FixtureCommon.java
Labels: chore

#16 chore: re-package app-common module
  app-common/src/main/java/io/fulflix/common/app/AppCommonConfig.java
  app-common/src/main/java/io/fulflix/common/app/context/UserContextConfig.java
  app-common/src/main/java/io/fulflix/common/app/context/UserContextHolder.java
  app-common/src/main/java/io/fulflix/common/app/context/UserContextHolderInterceptor.java
  app-common/src/main/java/io/fulflix/common/app/context/annotation/CurrentUser.java
  app-common/src/main/java/io/fulflix/common/app/context/annotation/CurrentUserArgumentResolver.java
  app-common/src/main/java/io/fulflix/common/app/context/annotation/CurrentUserResolverConfig.java
  app-common/src/main/java/io/fulflix/common/app/jpa/JpaConfig.java
  app-common/src/main/java/io/fulflix/common/app/jpa/audit/Auditable.java
  app-common/src/main/java/io/fulflix/common/app/jpa/audit/CommonAuditFields.java
  app-common/src/main/java/io/fulflix/common/app/jpa/audit/UserAuditorAwareConfig.java
Labels: chore

#18 config: auth-app logging 설정 추가
  auth-app/src/main/java/io/fulflix/auth/AuthApp.java
  auth-app/src/main/resources/application-auth.yml
  auth-app/src/main/resources/application.yml
  auth-app/src/main/resources/properties/jwt.yml
  auth-app/src/main/resources/properties/logging.yml
Labels: config

#19 config: add jpa test base configurations
  app-common/build.gradle.kts
  app-common/src/test/java/io/fulflix/common/app/base/persistence/JpaTestBase.java
Labels: config

#20 feat: design user entity
  app-common/src/test/java/io/fulflix/common/app/base/persistence/JpaTestBase.java
  app-common/src/test/java/io/fulflix/common/app/config/TestUserAuditorAwareConfig.java
  user-app/src/main/java/io/fulflix/user/config/UserAuditable.java
  user-app/src/main/java/io/fulflix/user/repo/UserRepo.java
  user-app/src/main/java/io/fulflix/user/repo/model/Role.java
  user-app/src/main/java/io/fulflix/user/repo/model/User.java
  user-app/src/test/java/io/fulflix/user/repo/UserRepoTest.java
Labels: enhance, feat, test

#22 config: global exception handler
  auth-app/src/main/java/io/fulflix/auth/api/AuthController.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/SignInRequest.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/SignUpRequest.java
  auth-app/src/main/java/io/fulflix/auth/exception/AuthException.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthApiTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthControllerTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  web-common/build.gradle.kts
  web-common/src/main/java/io/fulflix/common/web/WebCommonConfig.java
  web-common/src/main/java/io/fulflix/common/web/exception/BusinessException.java
  web-common/src/main/java/io/fulflix/common/web/exception/event/StackTraceExtractor.java
  web-common/src/main/java/io/fulflix/common/web/exception/event/ThrowsExceptionEvent.java
  web-common/src/main/java/io/fulflix/common/web/exception/event/ThrowsExceptionEventListener.java
  web-common/src/main/java/io/fulflix/common/web/exception/handler/GlobalExceptionHandler.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/GlobalErrorCode.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/GlobalErrorResponse.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/MethodArgumentNotValidErrorResponse.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/validation/ErrorDetail.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/validation/ErrorDetails.java
  web-common/src/main/java/io/fulflix/common/web/utils/ResponseEntityUtils.java
  web-common/src/main/java/io/fulflix/common/web/utils/UriComponentUtils.java
Labels: build, config, enhance, feat, refactor, test

#23 fix: remove fixture-monkey dependency
  auth-app/src/test/java/io/fulflix/auth/api/AuthApiTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthControllerTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthServiceTestHelper.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/fixture/AuthTestFixture.java
  auth-app/src/test/java/io/fulflix/auth/utils/jwt/JwtProviderTest.java
  auth-app/src/test/java/io/fulflix/auth/utils/jwt/TokenTestHelper.java
  build.gradle
  web-common/src/test/java/io/fulflix/common/web/fixture/FixtureCommon.java
Labels: fix, test

#24 chore: auth-app 코드 정리
  auth-app/src/main/java/io/fulflix/auth/api/dto/UserCreateRequest.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
  auth-app/src/main/java/io/fulflix/infra/client/dto/UserResponse.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthControllerTest.java
Labels: chore

#25 fix: add-handler-missing-no-resource-found-exception
  web-common/src/main/java/io/fulflix/common/web/exception/handler/GlobalExceptionHandler.java
  web-common/src/main/java/io/fulflix/common/web/exception/response/GlobalErrorCode.java
Labels: fix

#27 feat: retrieve user credential api
  user-app/src/main/java/io/fulflix/user/api/UserController.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/UserAuthenticateController.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/dto/UserAuthorityCreateRequest.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/dto/UserCredentialResponse.java
  user-app/src/main/java/io/fulflix/user/application/UserAuthenticateUseCase.java
  user-app/src/main/java/io/fulflix/user/exception/UserErrorCode.java
  user-app/src/main/java/io/fulflix/user/exception/UserException.java
  user-app/src/main/java/io/fulflix/user/repo/UserRepo.java
  user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
  user-app/src/test/java/io/fulflix/user/api/UserApiTestHelper.java
  user-app/src/test/java/io/fulflix/user/api/UserControllerTest.java
  user-app/src/test/java/io/fulflix/user/api/authenticate/UserAuthenticateControllerTest.java
Labels: chore, feat

#28 build: add test task to root project
  build.gradle
Labels: build

#29 build: application local profiles configurations
  .gitignore
  app-common/build.gradle.kts
  app-common/src/main/resources/properties/datasource.yml
  app-common/src/main/resources/properties/jpa.yml
  auth-app/src/main/resources/application.yml
  docker-compose.yml
  user-app/src/main/resources/application-user.yml
Labels: build

#30 build: eureka 서버 module 생성
  build.gradle
  eureka/build.gradle
  eureka/src/main/java/io/fulflix/eureka/EurekaApp.java
  eureka/src/main/java/io/fulflix/eureka/config/SecurityConfig.java
  eureka/src/main/resources/application.yml
  settings.gradle
Labels: build

#33 config: 선언형 HTTP Client feign-client 사용을 위한 환경 설정 구성
  app-common/build.gradle.kts
  app-common/src/main/java/io/fulflix/common/app/feign/FeignClientConfig.java
  app-common/src/main/java/io/fulflix/common/app/feign/RequestHeaderInterceptor.java
Labels: build, config

#34 chore: rename authenticate process
  auth-app/src/main/java/io/fulflix/auth/api/AuthController.java
  auth-app/src/main/java/io/fulflix/auth/api/dto/CreatePrincipalRequest.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthenticationService.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
  auth-app/src/main/java/io/fulflix/infra/client/UserAppClient.java
  auth-app/src/main/java/io/fulflix/infra/client/dto/UserCredentialResponse.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/fixture/AuthTestFixture.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/UserAuthenticateController.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/dto/CreatePrincipalRequest.java
  user-app/src/main/java/io/fulflix/user/application/UserAuthenticateUseCase.java
  user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
Labels: style

#36 fix: sign up api response handling error
  auth-app/src/main/java/io/fulflix/auth/api/AuthController.java
  auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
  auth-app/src/main/java/io/fulflix/infra/client/UserAppClient.java
  auth-app/src/main/java/io/fulflix/infra/client/dto/UserResponse.java
  auth-app/src/test/java/io/fulflix/auth/api/AuthControllerTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
  auth-app/src/test/java/io/fulflix/auth/fixture/AuthTestFixture.java
  web-common/src/main/java/io/fulflix/common/web/utils/ResponseEntityUtils.java
Labels: fix

#37 Feature/hub
  hub-app/build.gradle
  hub-app/gradle/wrapper/gradle-wrapper.jar
  hub-app/gradle/wrapper/gradle-wrapper.properties
  hub-app/src/main/java/io/fulflix/hub/HubAppApplication.java
  hub-app/src/main/java/io/fulflix/hub/hub/api/HubController.java
  hub-app/src/main/java/io/fulflix/hub/hub/api/dto/HubRequestDto.java
  hub-app/src/main/java/io/fulflix/hub/hub/api/dto/HubResponseDto.java
  hub-app/src/main/java/io/fulflix/hub/hub/application/HubService.java
  hub-app/src/main/java/io/fulflix/hub/hub/domain/Hub.java
  hub-app/src/main/java/io/fulflix/hub/hub/domain/HubRepository.java
  hub-app/src/main/java/io/fulflix/hub/hub/exception/HubErrorCode.java
  hub-app/src/main/java/io/fulflix/hub/hub/exception/HubException.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteCreateDto.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteResponseDto.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRoute.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRouteRepository.java
  hub-app/src/main/resources/application.yml
  hub-app/src/test/java/io/fulflix/hub/HubAppApplicationTests.java
  settings.gradle
Labels: feat, refactor

#39 feat/add api-gateway module and jwt authorization filter
  docs/client/gateway.http
  gateway/build.gradle.kts
  gateway/src/main/java/io/fulflix/gateway/GatewayApp.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/exception/AuthErrorCode.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/exception/UnAuthorizedException.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/filter/AllowsAllRequestFilter.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/filter/JwtAuthorizationFilter.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/jwt/FulflixPrincipal.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/jwt/JwtProperties.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/jwt/JwtResolver.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/jwt/Role.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/utils/RequestHeaderUtils.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/utils/SigningUtils.java
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/properties/eureka.yml
  gateway/src/main/resources/properties/jwt.yml
  gateway/src/main/resources/properties/logging.yml
  gateway/src/main/resources/properties/routing.yml
  settings.gradle
Labels: build, config, docs, feat

#42 feat: user mypage
  app-common/src/main/java/io/fulflix/common/app/context/UserContextHolder.java
  docs/client/gateway.http
  gateway/src/main/resources/properties/routing.yml
  user-app/src/main/java/io/fulflix/user/api/mypage/UserMyPageController.java
  user-app/src/main/java/io/fulflix/user/api/mypage/dto/UserResponse.java
  user-app/src/main/java/io/fulflix/user/application/UserMyPageService.java
Labels: enhance, feat, fix

#43 feat: add current user role context and annotation
  app-common/src/main/java/io/fulflix/common/app/context/annotation/CurrentUserRole.java
  app-common/src/main/java/io/fulflix/common/app/context/annotation/resolver/CurrentUserArgumentResolver.java
  app-common/src/main/java/io/fulflix/common/app/context/annotation/resolver/CurrentUserRoleArgumentResolver.java
  app-common/src/main/java/io/fulflix/common/app/context/config/CurrentUserResolverConfig.java
  app-common/src/main/java/io/fulflix/common/app/context/config/UserContextConfig.java
  app-common/src/main/java/io/fulflix/common/app/context/holder/UserContextHolder.java
  app-common/src/main/java/io/fulflix/common/app/context/holder/UserRoleContextHolder.java
  app-common/src/main/java/io/fulflix/common/app/context/interceptor/UserContextHolderInterceptor.java
  app-common/src/main/java/io/fulflix/common/app/context/interceptor/UserRoleContextHolderInterceptor.java
  app-common/src/main/java/io/fulflix/common/app/feign/RequestHeaderInterceptor.java
  app-common/src/main/java/io/fulflix/common/app/jpa/audit/UserAuditorAwareConfig.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/dto/CreatePrincipalRequest.java
  user-app/src/main/java/io/fulflix/user/api/authenticate/dto/UserCredentialResponse.java
  user-app/src/main/java/io/fulflix/user/api/mypage/UserMyPageController.java
  user-app/src/main/java/io/fulflix/user/repo/model/Role.java
  user-app/src/main/java/io/fulflix/user/repo/model/User.java
  user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
  user-app/src/test/java/io/fulflix/user/repo/UserRepoTest.java
  web-common/src/main/java/io/fulflix/common/web/principal/Role.java
Labels: chore, config, enhance, feat, refactor

#44 build: zipkin for distributed trace
  app-common/src/main/resources/application.yml
  app-common/src/main/resources/properties/zipkin.yml
  auth-app/src/main/resources/application.yml
  auth-app/src/main/resources/properties/zipkin.yml
  build.gradle
  docker-compose.yml
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/properties/zipkin.yml
Labels: build, config

#47 chore: polishing gateway
  gateway/src/main/java/io/fulflix/gateway/authenticate/filter/AllowsAllRequestFilter.java
  gateway/src/main/java/io/fulflix/gateway/authenticate/utils/RequestHeaderUtils.java
Labels: chore

#50 config: 유레카 등록 설정
  docs/client/auth-app.http
  docs/client/hub-app.http
  gateway/src/main/resources/properties/routing.yml
  hub-app/build.gradle
  hub-app/src/main/java/io/fulflix/hub/HubAppApplication.java
  hub-app/src/main/java/io/fulflix/hub/hub/api/HubController.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteResponseDto.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteUpdateDto.java
  hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  hub-app/src/main/resources/application-hub.yml
  hub-app/src/main/resources/application.yml
Labels: config, enhance

#52 Build/company app
  company-app/build.gradle
  company-app/src/main/java/io/fulflix/company/CompanyApp.java
  company-app/src/main/resources/application-company.yml
  company-app/src/test/java/io/fulflix/company/CompanyAppTests.java
  settings.gradle
Labels: build, chore

#54 feat: apply create user username validation
  auth-app/src/test/java/io/fulflix/auth/application/AuthenticationServiceTest.java
  build.gradle
  user-app/src/main/java/io/fulflix/user/application/UserAuthenticateUseCase.java
  user-app/src/main/java/io/fulflix/user/exception/UserErrorCode.java
  user-app/src/main/java/io/fulflix/user/repo/UserRepo.java
  user-app/src/main/java/io/fulflix/user/repo/model/User.java
  user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
  user-app/src/test/java/io/fulflix/user/api/authenticate/UserAuthenticateControllerTest.java
  user-app/src/test/java/io/fulflix/user/application/UserAuthenticateUseCaseTest.java
  web-common/src/test/java/io/fulflix/common/web/base/presentation/OpenFeignClientTestBase.java
Labels: build, config, feat, test

#55 test: add user mypage api test case
  app-common/src/main/java/io/fulflix/common/app/context/interceptor/UserContextHolderInterceptor.java
  user-app/src/test/java/io/fulflix/user/api/UserApiTestHelper.java
  user-app/src/test/java/io/fulflix/user/api/mypage/UserMyPageControllerTest.java
Labels: test

#60 feat: 허브경로 삭제 구현
  docs/client/hub-app.http
  service/hub-app/src/main/java/io/fulflix/hub/hub/api/HubController.java
  service/hub-app/src/main/java/io/fulflix/hub/hub/application/HubService.java
  service/hub-app/src/main/java/io/fulflix/hub/hub/domain/Hub.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRoute.java
Labels: feat, fix

#61 Refactor/hub delete api
  docs/client/hub-app.http
  service/hub-app/src/main/java/io/fulflix/hub/hub/application/HubService.java
  service/hub-app/src/main/java/io/fulflix/hub/hub/domain/Hub.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRoute.java
Labels: chore, refactor

#62 build: delivery-app 모듈 세팅
  infrastructure/gateway/src/main/resources/properties/routing.yml
  service/delivery-app/build.gradle
  service/delivery-app/src/main/java/io/fulflix/delivery/DeliveryAppApplication.java
  service/delivery-app/src/main/resources/application-delivery.yml
  service/delivery-app/src/test/java/io/fulflix/delivery/DeliveryAppApplicationTests.java
Labels: build

#63 feat: user detail api
  docs/client/gateway.http
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/UserMyPageController.java
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/UserRetrieveController.java
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/dto/UserResponse.java
  service/user-app/src/main/java/io/fulflix/user/application/UserMyPageService.java
  service/user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
  service/user-app/src/test/java/io/fulflix/user/api/UserApiTestHelper.java
  service/user-app/src/test/java/io/fulflix/user/api/mypage/UserMyPageControllerTest.java
  service/user-app/src/test/java/io/fulflix/user/api/retrieve/UserMyPageControllerTest.java
  service/user-app/src/test/java/io/fulflix/user/api/retrieve/UserRetrieveControllerTest.java
Labels: feat, refactor, test, style

#67 enhance: gateway를 통한 company-app 호출 및 현재 로그인한 사용자, 권한 설정 추가
  core/web-core/src/main/java/io/fulflix/common/web/principal/Role.java
  docs/client/company-app-user.http
  docs/client/company-app.http
  infrastructure/gateway/src/main/resources/properties/routing.yml
  service/company-app/src/main/java/io/fulflix/company/api/CompanyController.java
  service/company-app/src/main/java/io/fulflix/company/api/dto/RegisterCompanyRequest.java
  service/company-app/src/main/java/io/fulflix/company/application/CompanyService.java
  service/company-app/src/main/java/io/fulflix/company/domain/Company.java
  service/company-app/src/main/java/io/fulflix/company/exception/CompanyErrorCode.java
Labels: docs, enhance, feat, refactor, test

#69 feat: delivery 생성 구현
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/DeliveryController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/dto/DeliveryCreateDto.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/dto/DeliveryResponseDto.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/Delivery.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/DeliveryRepository.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/DeliveryStatus.java
Labels: feat

#70 feat:get users api
  core/app-core/src/test/java/io/fulflix/common/app/base/persistence/TestBaseFixtures.java
  docs/client/gateway.http
  docs/client/user-app.http
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/UserMyPageController.java
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/UserRetrieveController.java
  service/user-app/src/main/java/io/fulflix/user/application/UserRetrieveService.java
  service/user-app/src/test/java/io/fulflix/fixture/UserFixtures.java
  service/user-app/src/test/java/io/fulflix/user/api/UserApiTestHelper.java
  service/user-app/src/test/java/io/fulflix/user/api/retrieve/UserMyPageControllerTest.java
  service/user-app/src/test/java/io/fulflix/user/api/retrieve/UserRetrieveControllerTest.java
Labels: chore, feat, refactor, test

#72 test: extract intellij http-client local profiles environment
  docs/client/auth-app.http
  docs/client/company-app-user.http
  docs/client/company-app.http
  docs/client/config/http-client.env.json
  docs/client/delivery-app.http
  docs/client/gateway.http
  docs/client/hub-app.http
  docs/client/user-app.http
Labels: test

#73 Feature/배송 생성 & 추가 시 허브가 존재하는지 확인하는 로직 추가
  docs/client/auth-app.http
  docs/client/delivery-app.http
  docs/client/hub-app.http
  service/delivery-app/build.gradle
  service/delivery-app/src/main/java/io/fulflix/delivery/DeliveryAppApplication.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/exception/DeliveryErrorCode.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/infra/client/HubClient.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/infra/client/dto/HubResponseDto.java
  service/hub-app/build.gradle
  service/hub-app/src/main/java/io/fulflix/hub/HubAppApplication.java
  service/hub-app/src/main/java/io/fulflix/hub/hub/api/HubController.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
Labels: enhance

#74 refactor: delivery-app의 infra.client 경로 변경
  docs/client/auth-app.http
  service/delivery-app/build.gradle
  service/delivery-app/src/main/java/io/fulflix/delivery/DeliveryAppApplication.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/HubClient.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/dto/HubResponseDto.java
  service/hub-app/build.gradle
  service/hub-app/src/main/java/io/fulflix/hub/HubAppApplication.java
Labels: chore, refactor

#75 Feat/배송 조회, 검색, 삭제 기능 구현
  docs/client/delivery-app.http
  docs/client/hub-app.http
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/DeliveryController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/DeliveryRepository.java
Labels: docs, feat

#82 feature: enhance gateway authorization by security
  core/web-core/src/main/java/io/fulflix/common/web/principal/Role.java
  docs/client/auth-app.http
  infrastructure/gateway/build.gradle.kts
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/config/JwtReactiveSecurityContextRepository.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/config/ReactiveSecurityConfig.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/domain/FulflixPrincipal.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/domain/Role.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/filter/AllowsAllRequestFilter.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/filter/JwtAuthorizationFilter.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/jwt/JwtResolver.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/utils/RequestHeaderUtils.java
  infrastructure/gateway/src/main/java/io/fulflix/gateway/exception/GlobalReactiveExceptionHandler.java
  infrastructure/gateway/src/main/resources/properties/routing.yml
  service/auth-app/src/main/java/io/fulflix/auth/domain/Role.java
Labels: build, chore, config, enhance, feat, style

#83 Ci: local docker build configurations by jib
  build.gradle
  build.sh
  core/app-core/src/main/resources/logback-spring-dev.xml
  core/app-core/src/main/resources/properties/eureka.yml
  docker-compose.yml
  docker-compose/fulflix.yml
  infrastructure/eureka/build.gradle
  infrastructure/gateway/build.gradle.kts
  service/auth-app/build.gradle
  service/company-app/build.gradle
  service/delivery-app/build.gradle
  service/hub-app/build.gradle
  service/user-app/build.gradle
Labels: build, chore, ci, config

#84 chore: 전체 micro-service container를 포함하도록 docker-compose 수정
  docker-compose.yml
  docker-compose/fulflix.yml
Labels: build, chore

#86 fix: 허브 경로 생성 시 출발 허브와 도착 허브가 같을 경우 에러 처리
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/Delivery.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/exception/HubRouteErrorCode.java
Labels: chore, fix

#87 feat: Directions5 api로 이동 시간, 이동 거리 구하기
  docs/client/hub-app.http
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteCreateDto.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteResponseDto.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteUpdateDto.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRoute.java
  service/hub-app/src/main/java/io/fulflix/hub/infra/naver/application/NaverDirectionsService.java
  service/hub-app/src/main/java/io/fulflix/hub/infra/naver/application/NaverDirectionsServiceImpl.java
  service/hub-app/src/main/java/io/fulflix/hub/infra/naver/dto/RouteInfo.java
  service/hub-app/src/main/resources/application-hub.yml
Labels: feat, refactor

#89 feat: naver map direction5 api client
  core/app-core/src/main/java/io/fulflix/common/app/feign/FeignClientErrorDecoderConfig.java
  core/app-core/src/main/resources/properties/eureka.yml
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/NaverDirectionClient.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/NaverDirectionClientHeaderConfig.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/NaverRequestInterceptor.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/dto/Location.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/dto/RouteResponse.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/dto/RouteUnit.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/dto/Summary.java
  service/hub-app/src/main/java/io/fulflix/infra/client/external/naver/dto/Traoptimal.java
  service/hub-app/src/test/java/io/fulflix/infra/client/external/naver/NaverDirectionClientTest.java
Labels: build, config, feat, test

#90 fix: remove fulfilx principal to feign client request header interceptor configurations
  core/app-core/src/main/java/io/fulflix/common/app/feign/FeignClientConfig.java
  core/app-core/src/main/java/io/fulflix/common/app/feign/FulflixPrincipalRequestHeaderInterceptor.java
Labels: fix

#91 feat: 상품 등록 api
  docs/client/config/http-client.env.json
  docs/client/product-app.http
  service/company-app/src/main/java/io/fulflix/company/api/dto/CompanyDetailResponse.java
  service/company-app/src/main/java/io/fulflix/company/api/dto/CompanyResponse.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyClient.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyResponse.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyService.java
  service/product-app/src/main/java/io/fulflix/infra/client/exception/CompanyErrorCode.java
  service/product-app/src/main/java/io/fulflix/infra/client/exception/CompanyException.java
  service/product-app/src/main/java/io/fulflix/product/api/ProductController.java
  service/product-app/src/main/java/io/fulflix/product/api/dto/RegisterProductRequest.java
  service/product-app/src/main/java/io/fulflix/product/application/ProductFacade.java
  service/product-app/src/main/java/io/fulflix/product/application/ProductRegisterStrategy.java
  service/product-app/src/main/java/io/fulflix/product/application/strategy/HubCompanyRegisterProduct.java
  service/product-app/src/main/java/io/fulflix/product/application/strategy/MasterAdminRegisterProduct.java
  service/product-app/src/main/java/io/fulflix/product/application/validator/ProductValidator.java
  service/product-app/src/main/java/io/fulflix/product/config/ProductAuditable.java
  service/product-app/src/main/java/io/fulflix/product/domain/Product.java
  service/product-app/src/main/java/io/fulflix/product/exception/ProductErrorCode.java
  service/product-app/src/main/java/io/fulflix/product/exception/ProductException.java
  service/product-app/src/main/java/io/fulflix/product/repo/ProductRepo.java
Labels: feat

#95 build: separate fulflix application from docker compose
  README.md
  deploy.sh
  docker-compose.yml
  fulflix-compose.yml
  service/hub-app/src/test/java/io/fulflix/infra/client/external/naver/NaverDirectionClientTest.java
  stop.sh
Labels: build, docs

#96 feat: 상품 단일 조회 api
  docs/client/product-app.http
  service/product-app/src/main/java/io/fulflix/product/api/ProductController.java
  service/product-app/src/main/java/io/fulflix/product/application/ProductService.java
  service/product-app/src/main/java/io/fulflix/product/repo/ProductRepo.java
Labels: feat

#98 deliveryroute 도메인 생성
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/DeliveryRouteController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/dto/DeliveryRouteRequest.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/domain/DeliveryRoute.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/domain/DeliveryRouteRepo.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/domain/DeliveryRouteStatus.java
  service/hub-app/src/main/java/io/fulflix/hub/hub/domain/Hub.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteGenerator.java
  service/hub-app/src/main/java/io/fulflix/hub/infra/naver/application/NaverDirectionsService.java
Labels: chore, feat

#100 build: order-app 모듈 세팅
  fulflix-compose.yml
  infrastructure/gateway/src/main/resources/properties/routing.yml
  service/order-app/build.gradle
  service/order-app/src/main/java/io/fulflix/order/OrderApp.java
  service/order-app/src/main/resources/application-order.yml
  service/order-app/src/test/java/io/fulflix/order/OrderAppTests.java
Labels: build

#102 enhance: FulflixPrincipalRequestHeaderInterceptor를 사용하여 관리자 등록한 상품을 현재 로그인한 업체도 수정 가능할 수 있도록 개선
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyClient.java
  service/product-app/src/main/java/io/fulflix/product/application/strategy/HubCompanyUpdateProduct.java
Labels: enhance, feat

#101 feat: 최단 경로 api 구현
  docs/client/hub-app.http
  docs/client/shortestpath.http
  service/hub-app/build.gradle
  service/hub-app/src/main/java/io/fulflix/hub/hub/domain/Hub.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/DeliveryRouteRequest.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/ShortestPathRequest.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteGenerator.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/ShortestPathAlgorithm.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/domain/HubRoute.java
  service/hub-app/src/main/resources/application-hub.yml
  service/hub-app/src/test/java/io/fulflix/hub/ShortestPathTest.java
Labels: docs, feat, fix

#106 feat: 배송 경로 생성 api
  docs/client/delivery-app.http
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/dto/DeliveryResponseDto.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/domain/Delivery.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/DeliveryRouteController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/dto/DeliveryRouteResponse.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/application/DeliveryRouteService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/domain/DeliveryRoute.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/HubRouteClient.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/dto/DeliveryRouteRequest.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/dto/ShortestPathRequest.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/dto/ShortestPathResponse.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/ShortestPathResponse.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/ShortestPathAlgorithm.java
Labels: feat, refactor

#103 build: query dsl configuration for product app
  .gitignore
  core/app-core/build.gradle.kts
  core/app-core/src/test/java/io/fulflix/common/app/base/persistence/JpaTestBase.java
  service/product-app/build.gradle
  service/product-app/src/main/java/io/fulflix/product/api/dto/ProductDetailResponse.java
  service/product-app/src/main/java/io/fulflix/product/api/dto/ProductResponse.java
  service/product-app/src/main/java/io/fulflix/product/application/strategy/HubCompanyRegisterProduct.java
  service/product-app/src/main/java/io/fulflix/product/application/strategy/MasterAdminRegisterProduct.java
  service/product-app/src/main/java/io/fulflix/product/config/ProductAuditable.java
  service/product-app/src/main/java/io/fulflix/product/config/QueryDslConfig.java
  service/product-app/src/main/java/io/fulflix/product/repo/ProductQueryRepo.java
  service/product-app/src/test/java/io/fulflix/product/config/TestQueryDslConfig.java
  service/product-app/src/test/java/io/fulflix/product/repo/ProductQueryRepoTest.java
Labels: build, chore, config, enhance, feat, refactor, test

#109 chore: 각 모듈별, API 메소드별 구현된 개수 집계 및 전체 API 구현 통계 출력을 위한 스크립트 구현
  fulflix-statistics.sh
Labels: chore

#110 feat: 배송 경로 조회, 수정, 삭제
  docs/client/delivery-app.http
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/DeliveryRouteController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/dto/DeliveryRouteResponse.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/api/dto/DeliveryRouteUpdate.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/application/DeliveryRouteService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/domain/DeliveryRoute.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/exception/DeliveryRouteErrorCode.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/exception/DeliveryRouteException.java
Labels: feat

#112 feat: 주문 전체 조회 및 검색 api
  service/order-app/src/main/java/io/fulflix/order/api/OrderController.java
  service/order-app/src/main/java/io/fulflix/order/api/dto/OrderDetailResponse.java
  service/order-app/src/main/java/io/fulflix/order/application/OrderFacade.java
  service/order-app/src/main/java/io/fulflix/order/application/OrderRetrieveStrategy.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/HubAdminRetrieve.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/HubCompanyRetrieve.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/MasterAdminRetrieve.java
  service/order-app/src/main/java/io/fulflix/order/repo/OrderRepo.java
Labels: feat

#111 fix: 허브, 허브경로의 생성, 수정, 삭제를 마스터 관리자만 가능하게 수정
  docs/client/hub-app.http
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/config/ReactiveSecurityConfig.java
Labels: fix

#114 build: swagger for api docs
  core/app-core/build.gradle.kts
  core/app-core/src/main/java/io/fulflix/common/app/swagger/SwaggerConfig.java
  core/app-core/src/main/resources/application.yml
  core/app-core/src/main/resources/properties/swagger.yml
  core/web-core/src/main/java/io/fulflix/common/web/exception/event/ThrowsExceptionEventListener.java
Labels: build, docs

#115 fix: 배송, 배송경로의 PUT 요청권한 수정
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/config/ReactiveSecurityConfig.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteGenerator.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/ShortestPathAlgorithm.java
  service/hub-app/src/main/java/io/fulflix/hub/infra/naver/application/NaverDirectionsServiceImpl.java
Labels: chore, fix

#116 fix: remove set created by auditing feilds from company register process
  service/company-app/src/main/java/io/fulflix/company/api/CompanyController.java
  service/company-app/src/main/java/io/fulflix/company/application/CompanyService.java
  service/company-app/src/main/java/io/fulflix/company/repo/CompanyRepo.java
Labels: chore, fix, refactor

#117 feat: re-adjust pageable using custom argument resolver
  core/app-core/src/main/java/io/fulflix/common/app/context/config/WebConfig.java
  core/app-core/src/main/java/io/fulflix/common/app/jpa/pageable/FixedPageableHandlerMethodArgumentResolver.java
  docs/client/user-app.http
Labels: config, enhance, feat

#119 feat: 주문 수정 api
  docs/client/order-app.http
  service/order-app/src/main/java/io/fulflix/order/api/OrderController.java
  service/order-app/src/main/java/io/fulflix/order/api/dto/UpdateOrderRequest.java
  service/order-app/src/main/java/io/fulflix/order/application/OrderFacade.java
  service/order-app/src/main/java/io/fulflix/order/application/OrderUpdateStrategy.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/HubCompanyCancelOrder.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/HubCompanyUpdateOrder.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/MasterAdminUpdateOrder.java
  service/order-app/src/main/java/io/fulflix/order/domain/Order.java
Labels: feat, fix

#122 refactor: 최단 경로 생성 엔드포인트 변경
  docs/client/hub-app.http
  docs/client/shortestpath.http
  infrastructure/gateway/src/main/java/io/fulflix/gateway/authenticate/config/ReactiveSecurityConfig.java
  infrastructure/gateway/src/main/resources/properties/routing.yml
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/HubRouteController.java
Labels: refactor

#124 refactor: 허브경로 생성시 거리제한 추가
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteGenerator.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/exception/HubRouteErrorCode.java
Labels: refactor

#127 fix: 주문 생성 시 배송 경로 생성 오류 수정
  docs/client/delivery-app.http
  docs/client/delivery-scenario/dummy-data.http
  docs/client/order-app.http
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/api/DeliveryController.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/infra/client/HubRouteClient.java
  service/order-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/order-app/src/main/java/io/fulflix/infra/client/delivery/DeliveryRequest.java
  service/order-app/src/main/java/io/fulflix/infra/client/product/ProductDetailResponse.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/MasterAdminCreateOrder.java
Labels: fix

#128 Fix/deserialize boolean type is naming remove error
  core/app-core/src/main/java/io/fulflix/core/app/jpa/audit/CommonAuditFields.java
  service/auth-app/src/test/java/io/fulflix/auth/application/AuthorizationServiceTest.java
  service/company-app/src/main/java/io/fulflix/company/api/dto/CompanyDetailResponse.java
  service/company-app/src/main/java/io/fulflix/company/application/strategy/HubAdminDeleteStrategy.java
  service/company-app/src/main/java/io/fulflix/company/application/strategy/MasterAdminDeleteStrategy.java
  service/delivery-app/src/main/java/io/fulflix/delivery/delivery/application/DeliveryService.java
  service/delivery-app/src/main/java/io/fulflix/delivery/deliveryroute/application/DeliveryRouteService.java
  service/hub-app/gradle/wrapper/gradle-wrapper.jar
  service/hub-app/gradle/wrapper/gradle-wrapper.properties
  service/hub-app/src/main/java/io/fulflix/hub/hub/application/HubService.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteResponseDto.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/application/HubRouteService.java
  service/order-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/order-app/src/main/java/io/fulflix/infra/client/product/ProductDetailResponse.java
  service/order-app/src/main/java/io/fulflix/order/api/dto/OrderDetailResponse.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/HubCompanyCancelOrder.java
  service/order-app/src/main/java/io/fulflix/order/application/strategy/MasterAdminCancelOrder.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/product-app/src/main/java/io/fulflix/product/api/dto/ProductDetailResponse.java
  service/product-app/src/main/java/io/fulflix/product/application/ProductService.java
Labels: fix

#129 fix: Boolean isDeleted filed data type to boolean and apply @JsonProperty
  service/company-app/src/main/java/io/fulflix/company/api/dto/CompanyDetailResponse.java
  service/hub-app/src/main/java/io/fulflix/hub/hubroute/api/dto/HubRouteResponseDto.java
  service/order-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/order-app/src/main/java/io/fulflix/infra/client/product/ProductDetailResponse.java
  service/order-app/src/main/java/io/fulflix/order/api/dto/OrderDetailResponse.java
  service/product-app/src/main/java/io/fulflix/infra/client/company/CompanyDetailResponse.java
  service/product-app/src/main/java/io/fulflix/product/api/dto/ProductDetailResponse.java
Labels: fix

#134 feat: 회원 탈퇴 API 구현
  docs/client/user-app.http
  service/user-app/src/main/java/io/fulflix/user/api/retrieve/UserMyPageController.java
  service/user-app/src/main/java/io/fulflix/user/application/UserMyPageService.java
  service/user-app/src/main/java/io/fulflix/user/application/UserRetrieveService.java
Labels: feat, refactor

#135 docs: add README
  README.md
  docs/image/img.png
  docs/image/img_1.png
  docs/image/img_2.png
  docs/image/img_3.png
  docs/image/img_4.png
  docs/image/img_5.png
  docs/image/img_6.png
Labels: docs

#136 fix: edit diagrams
  README.md
  docs/image/img7.png
  docs/image/img8.png
Labels: docs

#137 fix: edit docs
  README.md
Labels: docs

#139 fix: 회원 생성 성공 시 http status 응답 체크 오류 수정
  service/auth-app/src/main/java/io/fulflix/auth/application/AuthorizationService.java
Labels: fix

#141 chore: prometheus docker compose 분리
  docker-compose.yml
  prometheus-compose.yml
Labels: chore

#145 build: Spring Kafka 의존성 추가 및 Docker Compose 설정
  service/order-app/build.gradle
  service/order-app/docker-compose.yml
Labels: build, config
